import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  MenuOutline,
  BarChartOutline,
  ShoppingOutline,
  SolutionOutline,
  AuditOutline,
  PlusOutline,
  InfoCircleOutline,
  GoogleOutline,
  UnorderedListOutline,
  RedoOutline,
  MinusOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ReadOutline,
  UserOutline,
  BankOutline,
  EnvironmentOutline,
  PrinterOutline,
  PhoneOutline,
  TeamOutline,
  HomeFill,
  AppstoreOutline,
  FolderOutline,
  FireOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline, MenuUnfoldOutline, FormOutline,
  ShoppingOutline, MenuOutline, BarChartOutline,
  SolutionOutline, AuditOutline, PlusOutline,
  InfoCircleOutline, GoogleOutline, UnorderedListOutline,
  RedoOutline, MinusOutline, ArrowLeftOutline,
  ReadOutline, UserOutline, BankOutline,
  PrinterOutline, PhoneOutline, TeamOutline,
  HomeFill, AppstoreOutline, FolderOutline,
  ArrowRightOutline, EnvironmentOutline, FireOutline
];
